# Generated by Django 5.1.6 on 2025-02-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_subtitle',
            field=models.CharField(default='Default Subtitle', max_length=86),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
