# Generated by Django 5.1.6 on 2025-02-13 10:59

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstBlog', '0005_post_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('title_tag', models.CharField(blank=True, max_length=45, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='img/')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
